apiVersion: v1
kind: ConfigMap
metadata:
  namespace: aptly
  name: ftech-apt-config
data:
  Caddyfile: |-
    :80 {
      root * /aptly-fs/ftech_public
      file_server browse
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aptly
  name: ftech-apt-repo
  labels:
    app: ftech-apt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftech-apt
  template:
    metadata:
      labels:
        app: ftech-apt
    spec:
      volumes:
      - name: ftech-apt-config-vol
        configMap:
          name: ftech-apt-config
          items:
          - key: "Caddyfile"
            path: "Caddyfile"
      - name: aptly-storage
        persistentVolumeClaim:
          claimName: aptly-volume
      containers:
      - name: repo
        image: "caddy:2.7.5"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ftech-apt-config-vol
            mountPath: "/etc/caddy/"
          - name: aptly-storage
            mountPath: "/aptly-fs"
---
apiVersion: v1
kind: Service
metadata:
  namespace: aptly
  name: ftech-apt-repo
  labels:
    app: ftech-apt
spec:
  type: ClusterIP
  selector:
    app: ftech-apt
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: aptly
  name: ftech-apt-repo
  labels:
    app: ftech-apt
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pkg.feliciano.tech
    secretName: ftech-apt-repo-tls
  rules:
  - host: pkg.feliciano.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ftech-apt-repo
            port:
              number: 80
